FROM krallin/centos-tini:centos7
MAINTAINER Heather Kelly <heather@slac.stanford.edu>

RUN yum update -y && \
    yum install -y bash \
    bison \
    blas \
    bzip2-devel \
    bzip2 \
    centos-release-scl \
    cmake \
    curl \
    dpkg \
    flex \
    fontconfig \
    freetype-devel \
    gcc-c++ \
    gcc-gfortran \
    gettext \
    git \
    glibc \
    glibc-devel \
    glib2.0-devel \
    java-1.8.0-openjdk \
    libuuid-devel \
    libselinux \
    libXext \
    libXrender \
    libXt-devel \
    make \
    mesa-libGLU \
    mesa-libGLU-devel \
    ncurses-devel \
    openssl-devel \
    patch \
    perl \
    perl-ExtUtils-MakeMaker \
    readline-devel \
    sed \
    tar \
    which \
    zlib \
    zlib-devel 

RUN yum install -y devtoolset-6 wget && \
    yum clean -y all

RUN rm -rf /var/cache/yum

#RUN groupadd -g 1000 -r lsst && useradd -u 1000 --no-log-init -m -r -g lsst lsst

#USER lsst

RUN source scl_source enable devtoolset-6 

RUN echo "Environment: \n" && env | sort

RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm -f ~/anaconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN export PATH=/opt/conda/bin:$PATH && \
    conda install -y cmake automake swig && \
    pip install colossus && \ 
    pip install pyccl
 
#    /opt/conda/bin/conda install -y -c conda-forge numcosmo

ENTRYPOINT [ "/usr/bin/tini", "--" ]
CMD [ "/bin/bash" ]



