FROM centos:7
MAINTAINER Heather Kelly <heather@slac.stanford.edu>

RUN yum update -y && \
    yum install -y bash \
    bison \
    blas \
    bzip2-devel \
    bzip2 \
    centos-release-scl \
    cmake \
    curl \
    flex \
    fontconfig \
    freetype-devel \
    gcc-c++ \
    gcc-gfortran \
    gettext \
    git \
    glibc \
    glibc-devel \
    glib2.0-devel \
    java-1.8.0-openjdk \
    libuuid-devel \
    libselinux \
    libXext \
    libXrender \
    libXt-devel \
    make \
    ncurses-devel \
    openssl-devel \
    patch \
    perl \
    perl-ExtUtils-MakeMaker \
    readline-devel \
    tar \
    which \
    zlib \
    zlib-devel 

RUN yum install -y devtoolset-6 && \
    yum clean -y all

RUN rm -rf /var/cache/yum

RUN groupadd -g 1000 -r lsst && useradd -u 1000 --no-log-init -m -r -g lsst lsst

ARG LSST_STACK_DIR=/opt/lsst/software/stack
ARG EUPS_HOME=$LSST_STACK_DIR/.eups
ARG EUPS_PRODUCT=lsst_apps
ARG EUPS_PRODUCT2=lsst_sims
ARG EUPS_TAG2=sims

RUN mkdir -p $LSST_STACK_DIR
RUN mkdir -p $EUPS_HOME

WORKDIR $LSST_STACK_DIR

RUN chown lsst $LSST_STACK_DIR
RUN chown lsst $EUPS_HOME
RUN chgrp lsst $LSST_STACK_DIR
RUN chgrp lsst $EUPS_HOME

USER lsst

RUN source scl_source enable devtoolset-6 

#ENTRYPOINT ["scl", "enable" "devtoolset-6", "--", "bash", "-c"]

RUN echo "Environment: \n" && env | sort

RUN echo "Executing: eups distrib install $EUPS_PRODUCT $EUPS_TAG" && \
    source scl_source enable devtoolset-6 && \
    curl -OL https://raw.githubusercontent.com/lsst/lsst/master/scripts/newinstall.sh && \
    bash newinstall.sh -b -3 && \
    echo -e "source scl_source enable devtoolset-6\n$(cat loadLSST.bash)" > loadLSST.bash && \
    /bin/bash -c 'source $LSST_STACK_DIR/loadLSST.bash; \
                  eups distrib install ${EUPS_TAG2:+"-t"} $EUPS_TAG2 $EUPS_PRODUCT --nolocks; \
                  eups distrib install ${EUPS_TAG2:+"-t"} $EUPS_TAG2 $EUPS_PRODUCT2 --nolocks;'

RUN rm -Rf python/doc
RUN rm -Rf python/phrasebooks
RUN find stack -name "*.pyc" -delete
RUN (find stack -name "*.so" | xargs strip -s -p) || true
RUN (find stack -name "src" | xargs rm -Rf) || true
RUN (find stack -name "doc" | xargs rm -Rf) || true
RUN (find stack -name "tests" | xargs rm -Rf ) || true


