FROM hepcce/desc_imsim:base_py3_v1

RUN zypper install -y time
RUN /bin/bash -c 'source /lsst/stack/loadLSST.bash; \
    cd /lsst; \
    git clone https://github.com/LSSTDESC/imSim.git; \
    cd imSim; \
    setup lsst_sims;\ 
    eups declare -r . imsim -t current; \
    setup imsim; \
    setup sconsUtils; \
    scons;'
